### PR TITLE
s22-6pm-2 Yufei replace stub with course search service

### PR DESCRIPTION
**Pull request by Sean-syf**
Replaced STUB function with the service created in #57 
In the add endpoints, it checks for a valid enrollCd and then try to search the course.
If no course with the given enrollCd is found in that quarter, it returns a CourseNotFoundException.
If course with the given enrollCd is found, then it adds the course to the data table.
Screen Shot 2022-06-01 at 2 54 49 PM

### CODE REVIEW

**Review by nirmitashar — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
The code looks good... though I'll want to test on QA before merging; and we probably need to merge a lot of other PRs first before we get to this one.

**Review by nirmitashar — APPROVED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
Tested changes on Heroku, including invalid quarters, invalid enroll codes, and user / admin functionality. Everything looks good!

**Comment by andrewhlu** [comment]
Everything looks good, but unsure whether to wait for earlier PRs to be merged before merging this one. Awaiting input from team in Slack.

**Comment by andrewhlu** [comment]
I'm going to merge this now but leave the points unassigned. Since this PR encompasses four previous PRs, I'll leave it up to @phtcon to assign a point value to this PR.

**Pull request merged**
