### PR TITLE
6pm-2 Heroku Production Deployment

### PR DESCRIPTION
**Pull request by mikeycurtis**
In this PR, I set up the production deployment on heroku, and updated the readme with links to the deployment and the dashboard.

### CODE REVIEW

**Review by Sean-syf — APPROVED** [review]
LGTM

**Review by andrewpengucsb — COMMENTED** [review]
Please resolve conflicts

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Review by austinmacmath — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Added @austinmacmath because he did the OAuth setup.

**Pull request merged**
