### PR TITLE
s22-6pm-2 Yufei List All Courses API

### PR DESCRIPTION
**Pull request by Sean-syf**
Created an API that returns all courses in the personal course database.

Screen Shot 2022-05-28 at 9 25 28 PM

### CODE REVIEW

**Review by austinmacmath — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM, modulo the fact that we may want to:
* remove yyyyq from the entity for PersonalCourses;
* the name of the PersonalCourses entity should probably be changed to PersonalCourse; we try to keep these singular.   I apologize for missing this before.
* we should do validation of the course (see issue https://github.com/ucsb-cs156-s22/s22-6pm-courses/issues/37 ) before it goes into the database, but that can be a separate issue.

This can be approved if it works; I'll test it out on QA before merging.

**Review by andrewhlu — COMMENTED** [review]
The changes in this PR looks good, and I've confirmed on Heroku that the changes work as intended. I didn't see any of the suggestions mentioned by @pconrad above addressed though.

Are you planning to address them here? If yes, I'll hold off on merging, but if not, I'll go ahead and formally approve / merge.

**Review by andrewhlu — APPROVED** [review]
LGTM. Per Slack communications, suggestions requested by @pconrad will be addressed in a future PR. I'm going to go ahead and merge this in the meantime.

@Sean-syf - please create an issue for Conrad's suggestions above (and link to this PR)

**Pull request merged**
