### PR TITLE
s22-6pm-1 Aaditya updated section search table to distinguish between Lectures and Sections

### LINKED ISSUE #60: Update table to easily distinguish between Section and Lecture
- [x] Be able to easily distinguish between classes and sections
- [x] Table displays the information correctly with the correct columns 
- [x] Passes coverage, stryker, and eslint

### PR DESCRIPTION
**Pull request by AadityaChannabasappa**
Changed the Section Search Table so that Lectures and Sections are more easily distinguishable. This is added because it helps the UX so that the user won't mistake a lecture for a section. Closes #60. **Has been scrubbed for commented-out code.**
Before:
image

After:
image

### CODE REVIEW

**Review by SrijitBoinapally — DISMISSED** [review]
The section functions as described in the PR. The storybook also appears to be working.

**Review by notkevin12 — APPROVED** [review]
LGTM

**Review by notkevin12 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
