### PR TITLE
s22-6pm-1 - Added Section Search Table to Section Search Page

### LINKED ISSUE #17: Replace the placeholder for section search with a page that uses the same components as the existing course search to get info from the user, but that returns a section table instead of the table that is now part of the app.
- [x] Replace index page with the table
- [x] Table has headers, cells, and information which match the section information returned by the backend api.
- [x] Full test coverage and passing all string stryker and eslint tests.
- [x] Table functions as expected on QA Heroku.

### PR DESCRIPTION
**Pull request by AadityaChannabasappa**
Added CoursesWithSectionSearchTable to the Section Search page so the new page displays the table with the proper information. This change was made so users will be able to access the table from the application. Closes #17. **Has been scrubbed for commented-out code.**
Before:
image

After:
image

### CODE REVIEW

**Review by hanzemeng — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Review by notkevin12 — APPROVED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
Tested on Heroku after merge conflict resolution, looks great!

**Review by pconrad — COMMENTED** [review]
LGTM!

**Pull request merged**
