### PR TITLE
s22-6pm-1 Anuragh - added Section search drop-down menu to the navbar

### LINKED ISSUE #6: Add a "section search" to the navigation bar, with a link to a placeholder page for "section searches".
Add a "section search" to the navigation bar, with a link to a placeholder page for "section searches".

- [x] A "section search" entry appears in the navbar
- [x] Clicking "List Section Search" goes to a placeholder page
- [x] The placeholder page contains information specific to section searches (distinguishing it from other pages and eliminating possibility of going to the wrong page)
- [x] Full coverage, noeslint errors, and passing all Stryker mutation tests
- [x] Works as expected on Heroku QA

### PR DESCRIPTION
**Pull request by anuraghs**
Added Section search to the navbar in the frontend. Clicking it opens a drop-down menu with a single link to a "List Section Search" page. Clicking to the link goes to a placeholder page. Also added new tests for navbar and for index page. Closes #6.

## Storybook

https://ucsb-cs156-s22.github.io/s22-6pm-courses-docs-qa/storybook-qa/Anuragh-SectionSearch/?path=/story/components-nav-appnavbar--basic-logged-in-regular-user

## Before:

image

## After:

image
image
image

### CODE REVIEW

**Review by AadityaChannabasappa — APPROVED** [review]

**Review by AadityaChannabasappa — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
Please remove the .DS_Store file from the commit.

You may want to add .DS_Store to the .gitignore so that this doesn't happen again.

Also: please add a placeholder page that this link goes to.  Right now, following the link results in  blank screen.   That's not a good user experience.   Anything that gets merged into the main branch needs to be at least a reasonable user experience (e.g. a placeholder page.)

image

**Review by AadityaChannabasappa — CHANGES_REQUESTED** [review]
Remove the commented code in SectionSearchIndexPage.test

**Review by AadityaChannabasappa — APPROVED** [review]

**Review by andrewhlu — APPROVED** [review]
Placeholder page is now present, changes look good. Thanks!

**Pull request merged**
